import LoginPage from "@/components/login/login";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "UM-MANAGEMENT | LOGIN",
  description: "Generated by Coding Rider",
};
const Login = () => {
  return (
    <>
      <LoginPage></LoginPage>
    </>
  );
};

export default Login;
